routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'FrontController@index');
Route::get('post/{slug}', 'FrontController@show');


//Es para que los usuarios que no están registrados no puedan entrer a dicha vista.
Route::middleware(['auth'])->group(function () { 
    Route::resource('categories', 'CategoryController');
    Route::resource('posts', 'PostController');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable =[
        'user_id',
        'category_id',
        'title',
        'slug',
        'body',
        'image',
    ];

    public function category(){
        return $this->belongsTo('App\Category');
    }

    public function user(){
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;
use App\User;
use App\Category;
use App\Post;
use Auth;
use Session;
use Redirect;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();

        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //busca por el id en el modelo User al usuario que ya este registrado
        $user = User::find(Auth::User()->id);   

        //traigo todas las categorias
        $categories = Category::all();   
    
        return view('posts.create', compact('categories', 'user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $regla = [
            'title' => 'required',
            'body' => 'required',
            'image' => 'mimes:jpeg,bmp,png,jpg,gif|max:2000'
        ];

        $mensaje = [
            'title.required' => 'Para crear hay que llenar',
            'body.required' => 'Es necesario un contenido   ',
            'image.mimes' => 'El archivo debe corresponder a un formato de imagen',
            'image.max' => 'La imagen no debe ser mayor que 2 MB'
        ];
       
        $this->validate($request, $regla, $mensaje);

        $post = new Post($request->all());

        $post->slug = Str::slug($request->title);
    
        $post->save();

        if($request->file('image')){
            
            //despues de disk indicamos el driver que vamos a usar y en el metodo put idicamos en donde se va almacenar y con que nombre, se almacena en una carpeta que la crea automaticamente laravel pero le indicamos el nombre y se guarda con el nombre original de la imagen
            $nombre = Storage::disk('imaposts')->put('imagenes/posts',$request->file('image'));
            
            $post->fill(['image' => asset($nombre)])->save();
        }

        Session::flash('message', 'Publicación creada');

        return redirect()->route('posts.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);
        
        $categories = Category::all();

        return view('posts.edit', compact('post', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $regla = [
            'title' => 'required',
            'body' => 'required',
            'image' => 'mimes:jpeg,bmp,png,jpg,gif|max:2000'
        ];

        $mensaje = [
            'title.required' => 'Para crear hay que llenar',
            'body.required' => 'Es necesario un contenido   ',
            'image.mimes' => 'El archivo debe corresponder a un formato de imagen',
            'image.max' => 'La imagen no debe ser mayor que 2 MB'
        ];
       
        $this->validate($request, $regla, $mensaje);

        $post = Post::find($id);

        $post->slug = Str::slug($request->title);
    
        $post->update($request->all());

        if($request->file('image')){
            
            //despues de disk indicamos el driver que vamos a usar y en el metodo put idicamos en donde se va almacenar y con que nombre, se almacena en una carpeta que la crea automaticamente laravel pero le indicamos el nombre y se guarda con el nombre original de la imagen
            $nombre = Storage::disk('imaposts')->put('imagenes/post',$request->file('image'));
            
            $post->fill(['image' => asset($nombre)])->save();
        }

        Session::flash('message', 'Publicación actualizada');

        return redirect()->route('posts.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        
        $post->delete();

        Session::flash('message', 'Publicaión borrada');
        
        return redirect()->route('posts.index');
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header bg-primary text-white">Crear Publicaciones</div>
                    <form action="{{ route('posts.store') }}" method="POST" class="m-4 text-primary" enctype="multipart/form-data">
                        @csrf
                        <input type="hidden" name="user_id" value="{{ $user->id }}">
                        <div class="form-group">
                            <label class="form-control-label">Categorias</label>
                            <select name="category_id" class="form-control">
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="form-control-label">Titulo de la Publicación</label>
                            <input type="text" class="form-control form-control-alternative" name="title" value="{{ old('title') }}">
                            @if($errors->has('title'))
                                <strong class="text-danger">{{ $errors->first('title') }}</strong>
                            @endif  
                        </div>
                        <div class="form-group">
                            <label class="form-control-label">Contenido</label>
                            <textarea name="body" rows="3" class="form-control" value="{{ old('body') }}"></textarea>
                            @if($errors->has('body'))
                                <strong class="text-danger">{{ $errors->first('body') }}</strong>
                            @endif
                        </div>
                        <div class="form-group">
                            <label class="form-control-label">Portada</label>
                            <input type="file" class="form-control form-control-alternative" name="image">
                            @if($errors->has('image'))
                                <strong class="text-danger">{{ $errors->first('image') }}</strong>
                            @endif
                        </div>
                        <button type="submit" class="btn btn-primary m-4">Crear</button>
                    </form>
                </div>
            </div>
        </div>
        <a class="btn btn-dark m-5" href="{{ route('posts.index') }}"><- Volver</a>
    </div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header bg-success text-white">Editar Publicación</div>
                    <form action="{{ route('posts.update', $post->id) }}" method="POST" class="m-4 text-success" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label class="form-control-label">Categorias</label>
                            <select name="category_id" class="form-control">
                                <option value="{{ $post->category_id }}" selected="selected">{{ $post->category->name }}</option>
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="form-control-label">Titulo de la Publicación</label>
                            <input type="text" class="form-control form-control-alternative" name="title" value="{{ $post->title }}">
                            @if($errors->has('title'))
                                <strong class="text-danger">{{ $errors->first('title') }}</strong>
                            @endif  
                        </div>
                        <div class="form-group">
                            <label class="form-control-label">Contenido</label>
                            <textarea name="body" rows="3" class="form-control">{{ $post->body }}</textarea>
                            @if($errors->has('body'))
                                <strong class="text-danger">{{ $errors->first('body') }}</strong>
                            @endif
                        </div>
                        <img src="{{ $post->image }}" alt="" class="img-fluid" width="200" height="300">
                        <div class="form-group">
                            <label class="form-control-label">Portada</label>
                            <input type="file" class="form-control form-control-alternative" name="image" value="{{ $post->image }}">
                            @if($errors->has('image'))
                                <strong class="text-danger">{{ $errors->first('image') }}</strong>
                            @endif
                        </div>
                        <button type="submit" class="btn btn-success m-4">Actualizar</button>
                    </form>
                </div>
            </div>
        </div>
        <a class="btn btn-dark m-5" href="{{ route('posts.index') }}"><- Volver</a>
    </div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <a href="{{ route('posts.create') }}" class="btn btn-secondary mb-3">Crear Publicaciones</a>
                <div class="card">
                    @if(Session::has('message'))
                        <div class="alert alert-secondary">{{ Session::get('message') }}</div>
                    @endif
                    <div class="card-header">Lista de Publicaciones</div>
                    <table class="table">
                        <thead class="thead-dark">
                          <tr>
                            {{-- <th scope="col">id</th> --}}
                            <th scope="col">Titulo</th>
                            <th scope="col">Categorias</th>
                            {{-- <th scope="col">Autor</th> --}}
                            <th scope="col">Portada</th>
                            <th scope="col">Acción</th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach($posts as $post)
                                <tr>
                                    {{-- <th scope="row">{{$post->id}}</th> --}}
                                    <td>{{$post->title}}</td>
                                    <td>{{$post->category->name}}</td>
                                    {{-- <td>{{$post->user->name}}</td> --}}
                                    <td><img src="{{$post->image}}" alt="" width="75" height="75"></td>
                                    <td style="col">
                                        <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-success mb-2 w-100 ">Editar</a>
                                        <form action="{{ route('posts.destroy', $post->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger w-100" onclick="return cofirm('¿Seguro/a?')">Eliminar</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection