routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'FrontController@index');
Route::get('post/{slug}', 'FrontController@show');


//Es para que los usuarios que no están registrados no puedan entrer a dicha vista.
Route::middleware(['auth'])->group(function () { 
    Route::resource('categories', 'CategoryController');
    Route::resource('posts', 'PostController');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{

    //aquí llenamos los campos que están en la tabla de la BD
    protected $fillable =[
        'name'
    ];

    public function posts(){
        return $this->hasMany('App\Post');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use Session;
use Redirect;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //traemos todas las categorias y la guardamos en una variable
        $categories = Category::all();
       
        //con el compact pasamos los datos de la variable a un array en la vista(archivo index.blade.php)
        return view('categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //creamos la validación así no se permita crear categorias en blanco
        $regla= [
            'name' => 'required'
        ];

        $mensaje = [
            'name.required' => 'Para crear hay que llenar'
        ];
      
        $this->validate($request, $regla, $mensaje);
      
        //traemos todo lo que viene atravez del formulario con todos sus campos
        Category::create($request->all());
      
        //creamos una sesion con le metodo flash para que nos salga un mensaje por unos segundos y desaparesca
        Session::flash('message', 'Categoria creada');
      
        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //nos busca la categoria por su id
        $category = Category::find($id);
       
        return view('categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $regla = [
            'name' => 'required'
        ];

        $mensaje = [
            'name.required' => 'Para actualizar hay que llenar'
        ];
       
        $this->validate($request, $regla, $mensaje);

        $category = Category::find($id);
        
        $category->update($request->all());
        
        Session::flash('message', 'Categoria actualizada');
        
        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        
        $category->delete();

        Session::flash('message', 'Categoria borrada');
        
        return redirect()->route('categories.index');
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header bg-primary text-white">Crear Categoria</div>
                    <form action="{{ route('categories.store') }}" method="POST" class="m-4">
                        @csrf
                        <div class="form-group">
                            <label for="name" class="form-control-label">Nombre de la Categoria</label>
                            <input type="text" name="name" class="form-control form-control-alternative">
                            @if($errors->has('name'))
                                <strong class="text-danger">{{ $errors->first('name') }}</strong>
                            @endif
                        </div>
                        <button type="submit" class="btn btn-primary m-4">Crear</button>
                    </form>
                </div>
            </div>
        </div>
        <a class="btn btn-dark m-5" href="{{ route('categories.index') }}"><- Volver</a>
    </div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header bg-success text-white">Editar Categoria</div>
                    <form action="{{ route('categories.update', $category->id) }}" method="POST" class="m-4">
                        @csrf
                        @method('PUT'){{-- lo usamos porque estamos por actualizar el registro --}}
                        <div class="form-group">
                            <label for="name" class="form-control-label">Nombre de la Categoria</label>
                            <input type="text" name="name" class="form-control form-control-alternative" value="{{ $category->name }}">
                            @if($errors->has('name'))
                                <strong class="text-danger">{{ $errors->first('name') }}</strong>
                            @endif
                        </div>
                        <button type="submit" class="btn btn-success m-4">Actualizar</button>
                    </form>
                </div>
            </div>
        </div>
        <a class="btn btn-dark m-5" href="{{ route('categories.index') }}"><- Volver</a>
    </div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <a href="{{ route('categories.create') }}" class="btn btn-secondary mb-3">Crear Categoria</a>
                <div class="card">
                    @if(Session::has('message'))
                        <div class="alert alert-secondary">{{ Session::get('message') }}</div>
                    @endif
                    <div class="card-header">Lista de Categorias</div>
                    <table class="table table-dark">
                        <thead>
                          <tr>
                            <th scope="col">id</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Acciones</th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach ($categories as $category)
                                <tr>
                                    <th scope="row">{{$category->id}}</th>
                                    <td>{{$category->name}}</td>
                                    <td class="d-flex">
                                        <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-success mr-2 ">Editar</a>
                                        <form action="{{ route('categories.destroy', $category->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger" onclick="return cofirm('¿Seguro/a?')">Eliminar</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                      </table>
                </div>
            </div>
        </div>
    </div>
@endsection